<?xml version="1.0" encoding="utf-8"?>
<soap12:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope">
  <soap12:Body>
    <ClaimsKnockReq xmlns="https://soaps.xxx.com">
      <InsurerIdRq>ZBIX</InsurerIdRq>
      <Transaction>2024-10-18</Transaction>
      <LossDtRq>2024-10-2</LossDtRq>
      <PolicyNumberRq>string</PolicyNumberRq>
      <PolicyTypeCdRq>string</PolicyTypeCdRq>
      <ClaimOccurrenceRq>string</ClaimOccurrenceRq>
      <RegistrationRq>string</RegistrationRq>
      <PaymentAmtRq>decimal</PaymentAmtRq>
      <UserRq>string</UserRq>
      <InsurerIdRs>string</InsurerIdRs>
      <PolicyNumberRs>string</PolicyNumberRs>
      <ClaimOccurrenceRs>string</ClaimOccurrenceRs>
      <RegistrationRs>string</RegistrationRs>
    </ClaimsKnockReq>
  </soap12:Body>
</soap12:Envelope>